/**
 * Stage Configuration
 * Defines fixed opponents for each stage (5 per chapter)
 * All names match exactly with questions.json guest names
 *
 * GENERATED by scripts/generate-content.js — do not edit manually
 */

export const STAGE_CONFIG = [
  // Chapter 1: The Library — "What is Cholesterol?"
  [
    "Lipidus the Wise",
    "Nurse Heartwell",
    "The Cholesterol Sage",
    "Fatty the Friendly",
    "Elder Plaque"
  ],

  // Chapter 2: The Clinic — "Understanding Your Labs"
  [
    "Dr. Panela",
    "Lab Tech Luna",
    "The Number Cruncher",
    "Range Ranger",
    "Fasting Frank"
  ],

  // Chapter 3: The Lab — "LDL, ApoB, and Lp(a)"
  [
    "Professor Particle",
    "Apolipora",
    "The LDL Hunter",
    "Dense Debbie",
    "Lp(a) the Ghost"
  ],

  // Chapter 4: The Garden — "Diet and Lifestyle"
  [
    "Chef Olive",
    "Cardio Kate",
    "The Mediterranean Monk",
    "Fiber the Fox",
    "Coach Vitale"
  ],

  // Chapter 5: The Apothecary — "Medications"
  [
    "Dr. Statina",
    "Eze the Absorber",
    "PCSK9 the Guardian",
    "Inclisiran the Whisperer",
    "Omega Rex"
  ],

  // Chapter 6: The Temple — "Prevention and Risk"
  [
    "High Priestess Risk",
    "Calcium the Seer",
    "The Lifestyle Oracle",
    "Aspirin the Fallen",
    "Inflammation the Shadow"
  ]
];

export const STAGE_NAME_ALIASES = {};

/**
 * Get opponents for a specific stage (1-indexed)
 */
export function getStageOpponents(stageNumber) {
  const index = stageNumber - 1;
  if (index < 0 || index >= STAGE_CONFIG.length) {
    console.warn(`Invalid stage number: ${stageNumber}`);
    return [];
  }
  return STAGE_CONFIG[index];
}

/**
 * Get total number of stages
 */
export function getTotalStages() {
  return STAGE_CONFIG.length;
}

/**
 * Get the tier number for a guest by name (1-indexed)
 * Returns the tier/stage they appear in
 */
export function getGuestTier(guestName) {
  for (let tierIndex = 0; tierIndex < STAGE_CONFIG.length; tierIndex++) {
    const tier = STAGE_CONFIG[tierIndex];
    if (tier.includes(guestName)) {
      return tierIndex + 1;
    }
  }
  console.warn(`Guest "${guestName}" not found in StageConfig`);
  return 1;
}
