/**
 * QuestForge Constants
 * All user-visible strings and configuration.
 * Every brand string must be imported from here — zero hardcoded brand strings.
 *
 * Generated by QuestForge fork pipeline.
 * Do not scatter brand strings across components.
 */

// ─── Brand ──────────────────────────────────────────────────────
export const GAME_NAME = 'Heart Quest';
export const GAME_SUBTITLE = 'The Lipid Adventure';
export const GAME_SLUG = 'heart-quest';
export const GAME_URL = 'https://lipiwiz.com/play';
export const GAME_DESCRIPTION =
  'Explore the Village of Heartwell and learn about heart disease prevention through an RPG adventure.';
export const COMPANY_NAME = 'CORDOC LLC';
export const GAME_THEME = 'heart-health';
export const GITHUB_URL = ''; // No public repo yet

// ─── Meta / SEO ─────────────────────────────────────────────────
export const META_TITLE = `${GAME_NAME} - Learn Heart Health | Educational RPG`;
export const META_DESCRIPTION =
  'Explore the Village of Heartwell in this educational RPG. Battle heart health NPCs, answer quiz questions, and learn about cholesterol, lipids, and cardiovascular disease prevention. Free to play!';
export const META_KEYWORDS =
  'heart health, cholesterol, lipid education, educational game, RPG game, cardiovascular, health quiz, heart disease prevention, lipid management, heart quest';
export const META_AUTHOR = COMPANY_NAME;
export const OG_IMAGE_URL = `${GAME_URL}/OpenGraph.png`;

// ─── localStorage Keys ──────────────────────────────────────────
export const SAVE_KEY = 'heartquest_save_data';
export const MUTE_KEY = 'heartquest-muted';
export const TUTORIAL_SEEN_KEY = 'heartquest-tutorial-seen';
export const LOCAL_LEADERBOARD_KEY = 'heartquest-leaderboard';

// ─── NPC & Encounter Copy ───────────────────────────────────────
export const ENCOUNTER_MESSAGES = [
  'challenges you to a knowledge battle!',
  'has a question for you!',
  'is ready for a health quiz!',
  'would like to test your knowledge!',
  'wants to see what you know!',
  'waves you over for a challenge!',
  'spotted you and smiles!',
  'wants to talk heart health!',
  'is up for a quick challenge!',
  'invites you to a knowledge duel!',
  'wants to compare notes!',
  'has a 3-question challenge!',
  'is eager to share what they know!',
  'is ready to learn together!',
  'has a quiz waiting for you!',
  'is excited to test you!',
  'has a quick prompt for you!',
  'would love your take on this!',
  'is hosting a mini quiz!',
  'is curious what you\'d choose!',
  'has some insights to test!',
  'has a challenge worth sharing!',
  'is ready for round one!',
  'has a short quiz queued up!',
  'wants your best answer!',
  'is ready to hear your reasoning!',
  'has a question from the village!',
  'is ready for a quick round!',
  'would like your opinion!',
  'is ready to explore an idea!',
];

// ─── Battle Copy ────────────────────────────────────────────────
export const ENCOUNTER_PREFIX = 'challenges you to a knowledge battle!';
export const BATTLE_WIN = 'You captured';
export const BATTLE_LOSE = 'retreated';

// ─── Share Copy ─────────────────────────────────────────────────
export const SHARE_TITLE = (playerName, level) =>
  `${playerName} is a Level ${level} Heart Health Master!`;

export const CHALLENGE_TEXT = (npcName, score) =>
  `I scored ${score}% against ${npcName}. Can you beat me?`;

export const DYK_SHARE_SUFFIX = `\n\nLearn more: ${GAME_URL}`;

export const SHARE_CARD_FOOTER = `Play ${GAME_NAME} at ${GAME_URL.replace('https://', '')}`;

export const SHARE_LINKEDIN_TEXT = (stats, accuracy, capturedCount, totalGuests, capturedNames) => {
  const guestsLine = capturedNames.length > 0
    ? 'Captured NPCs: ' + capturedNames.join(', ')
    : '';

  return `Just completed some heart health quizzes in ${GAME_NAME}!

This is a fun way to learn about cholesterol, lipids, and cardiovascular health — it's like Pokemon but with heart health experts.

My stats:
- Level ${stats.level} adventurer
- ${stats.totalBattles} battles won
- ${accuracy} percent accuracy
- Captured ${capturedCount} of ${totalGuests} NPCs
${guestsLine ? '\n' + guestsLine : ''}

Test your heart health knowledge!

Play now: ${GAME_URL}`;
};

// ─── Tutorial Copy ──────────────────────────────────────────────
export const TUTORIAL_WALK = 'Walk around the village to find heart health NPCs.';

// ─── Title Screen ───────────────────────────────────────────────
export const TITLE_SCREEN_SUBTITLE = 'EXPLORE THE VILLAGE OF HEARTWELL';
export const TITLE_SCREEN_TAGLINE = 'Learn about heart health. Battle NPCs. Collect knowledge.';

// ─── Character Classes ─────────────────────────────────────────
export const CHARACTER_TYPES = [
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Wisdom seeker',
    tint: 0x6EA8FE,  // Blue
    icon: '\u{1F4D6}', // Open book emoji (rendered as text, not in-game)
  },
  {
    id: 'healer',
    name: 'Healer',
    description: 'Heart guardian',
    tint: 0x75D979,  // Green
    icon: '\u{1F49A}',
  },
  {
    id: 'knight',
    name: 'Knight',
    description: 'Brave protector',
    tint: 0xFF7B7B,  // Red
    icon: '\u{1F6E1}',
  },
  {
    id: 'explorer',
    name: 'Explorer',
    description: 'Curious wanderer',
    tint: 0xFFD700,  // Gold
    icon: '\u{1F9ED}',
  },
];

export const CHARACTER_CONTEXT_PLACEHOLDER = 'e.g. "A med student learning lipids"';
export const CHARACTER_CONTEXT_MAX_LENGTH = 200;

// ─── Mobile Warning ─────────────────────────────────────────────
export const MOBILE_WARNING = `${GAME_NAME} works best in landscape mode. Please rotate your device to play!`;

// ─── Collection Screen ──────────────────────────────────────────
export const COLLECTION_TITLE = `${GAME_NAME} Collection`;

// ─── Episode / Learn More ───────────────────────────────────────
export const LEARN_MORE_LABEL = 'Learn more about this topic';
export const CREDITS_LINK_URL = 'https://lipiwiz.com';
export const CREDITS_LINK_TEXT = 'Lipiwiz heart health topics';
export const CREDITS_TOOLTIP = `${GAME_NAME} is an educational RPG about heart health by ${COMPANY_NAME}. Learn about cholesterol, lipids, and cardiovascular disease prevention.`;
